export { default as Auth } from "./Auth/Auth"
export { default as CartPage } from "./CartPage"
export { default as Contact } from "./Contact/Contact"
export { default as Homepage } from "./Homepage/Homepage"
export { default as Menu } from "./Menu/Menu"
export { default as NotFound } from "./NotFound"
export { default as Offers } from "./Offers/Offers"
export { default as ProfilePage } from "./ProfilePage"
